// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Conntrack = newAsset("conntrack.c", "368e3590d8ab062bdcccab142d1b0f3920b60bdf23b0fb927471874dc8e21e0c")
