// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Http = newAsset("http.c", "9f09de8e65ef6d644335b2f2761f0f5fb7e551cf9b385a7ea4e7d700e2d226af")
