// Code generated by go generate; DO NOT EDIT.
//go:build linux_bpf
// +build linux_bpf

package runtime

var Tracer = newAsset("tracer.c", "47bf8d1add392fd16ee1ebdf9aff0debac97c327fbad2df37041ba69a75d8e47")
